// import type { Metadata } from "next";
import "./globals.css";
import "@/src/css/fontface.css";
import Image from "next/image";

import bodyBackground from "@/public/assets/img/abstract.jpg"
import Nav from "@/src/components/nav"


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en">
      <body>
        <div className="app-body">
          <Nav/>
          {children}
        </div>
        
          <div className="bodyBackground">
            <Image src={bodyBackground} alt="background"/>
          </div>
      </body>
    </html>
  );
}
